// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYiYyIWJGEjWJFXyxpVVC7waJDlqaMtZA',
    appId: '1:835620235882:web:e940d132c15ae69a073813',
    messagingSenderId: '835620235882',
    projectId: 'finflow-4c0ea',
    authDomain: 'finflow-4c0ea.firebaseapp.com',
    storageBucket: 'finflow-4c0ea.firebasestorage.app',
    measurementId: 'G-CD7Q4YVGCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTv79yQX_VhyIlIhR3TX5A6ssVJPj0ao',
    appId: '1:287157964374:android:66874dcbafce0dd94135f7',
    messagingSenderId: '287157964374',
    projectId: 'finflow-app-e0da6',
    storageBucket: 'finflow-app-e0da6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRhpvYAHIlsx9ctIS5U6ouuoIF5Qhrn8',
    appId: '1:835620235882:ios:03bfbbb94fa9938a073813',
    messagingSenderId: '835620235882',
    projectId: 'finflow-4c0ea',
    storageBucket: 'finflow-4c0ea.firebasestorage.app',
    iosBundleId: 'com.example.finflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsRhpvYAHIlsx9ctIS5U6ouuoIF5Qhrn8',
    appId: '1:835620235882:ios:03bfbbb94fa9938a073813',
    messagingSenderId: '835620235882',
    projectId: 'finflow-4c0ea',
    storageBucket: 'finflow-4c0ea.firebasestorage.app',
    iosBundleId: 'com.example.finflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYiYyIWJGEjWJFXyxpVVC7waJDlqaMtZA',
    appId: '1:835620235882:web:1a8e2926e19138c3073813',
    messagingSenderId: '835620235882',
    projectId: 'finflow-4c0ea',
    authDomain: 'finflow-4c0ea.firebaseapp.com',
    storageBucket: 'finflow-4c0ea.firebasestorage.app',
    measurementId: 'G-GK8FSR8N2S',
  );
}
